[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/janeilagan/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = " <div class='animate__animated animate__swing animate__infinite'>🦥</div>"
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "a wild and tangled ecosystem of notes, ideas and thoughts"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "home"
# (Optional) Site title on landing page
LANDING_TITLE = "<span class='hvr-grow'>welcome to my digital jungle</span>"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/janeilagan/digitaljungle"
# (Optional) Site title in navbar
SITE_TITLE = "digital jungle <span class='hvr-bob'>🍃</span>"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = "digital jungle"
# (REQUIRED) Netlify site URL
SITE_URL = "https://digitaljungle.netlify.app/"
# (Optional) Site Timezone
TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "date"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = "y"
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
# Page graph only shows directly connected nodes. Default: "".
LOCAL_GRAPH = "y"
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = "y"
# If "y", clicking on graph link replaces current tab. Else, page is opened in new tab. Default: "".
GRAPH_LINK_REPLACE = "y"
# (Optional, default blank) Additional footer content.
FOOTER = ""
# (Optional, default main) Root section name.
ROOT_SECTION_NAME = "main"
# (Optional) visjs graph options. Can remove if desired. Update the main.js as well if you want to change the colors
GRAPH_OPTIONS = """
        {
			autoResize: true,
        	nodes: {
        		shape: "dot",
				color: isDark() ? "#5FD068" : "#4B8673",
        		font: {
        			face: "Inter",
					color: isDark() ? "#c9cdd1" : "#616469",
					strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
				roundness: 1
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
				solver: "forceAtlas2Based",
	
        	},
        }
        """